### ISSUE TITLE
Content of container

### ISSUE THREAD

**Issue by GeraudK** [aws-samples/sagemaker-ml-workflow-with-apache-airflow#1]
I see [here](https://github.com/aws-samples/sagemaker-ml-workflow-with-apache-airflow/blob/master/src/dag_ml_pipeline_amazon_video_reviews.py#L81) that you are using a container to build a custom model. 

Would it be possible to have more details on how this container is structured and understand the input/output of the estimator for different channels (e.g. train, tune, etc.)?

**Comment by RajeshThallam** [comment]
Hi @GeraudK , we are not building a custom model here. The [container](https://github.com/aws-samples/sagemaker-ml-workflow-with-apache-airflow/blob/master/src/dag_ml_pipeline_amazon_video_reviews.py#L76) refers to the Amazon SageMaker's factorization-machines container (built-in algorithm).  You can refer about the [Factorization Machines](https://docs.aws.amazon.com/sagemaker/latest/dg/fact-machines.html) here.
