### ISSUE TITLE
Airflow not getting deployed on EC2

### ISSUE THREAD

**Issue by tapanh** [aws-samples/sagemaker-ml-workflow-with-apache-airflow#2]
Hi,

After running the CloudFormation script, it looks like the airflow install is broken. Can you please take a look?

"ImportError: No module named json"
[user-data.log](https://github.com/aws-samples/sagemaker-ml-workflow-with-apache-airflow/files/3403004/user-data.log)

user-data.log attached.

Thanks!

**Comment by RajeshThallam** [comment]
Hi @tapanh , an incompatible version of flask is breaking the airflow build and there is a PR on Airflow repo in progress to be merged to master. Here is the [JIRA](https://issues.apache.org/jira/projects/AIRFLOW/issues/AIRFLOW-4902) on issue reported with Airflow. Meanwhile, you can change [Cloudformation template](https://github.com/aws-samples/sagemaker-ml-workflow-with-apache-airflow/blob/master/cfn/airflow-ec2.yaml#L107) to update Flask dependencies as mentioned on [Stackoverflow](https://stackoverflow.com/a/56923277/6069517).

**Comment by mpdominguez** [comment]
Corrected, thanks!
