### ISSUE TITLE
Sagemaker error when deployed on EC2

### ISSUE THREAD

**Issue by Phelan164** [aws-samples/sagemaker-ml-workflow-with-apache-airflow#3]
Hi guys,

I install sagemaker==v1.40.0

After I launch CloudFormation, I get error on EC2 log
ClientError: An error occurred (ValidationException) when calling the CreateModel operation: 2 validation errors detected: Value '{{ ti.xcom_pull(task_ids='model_training')['Training']['TrainingJobName'] }}' at 'modelName' failed to satisfy constraint: Member must have length less than or equal to 63; Value '{{ ti.xcom_pull(task_ids='model_training')['Training']['TrainingJobName'] }}' at 'modelName' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*

Note: I checked with sagemaker==v1.39.2 ==> it worked

**Comment by mpdominguez** [comment]
Please try it now, it should be working
