### ISSUE TITLE
sagemaker version - get_image_uri() not resolved

### ISSUE THREAD

**Issue by shekarchi** [aws-samples/sagemaker-ml-workflow-with-apache-airflow#5]
I am trying to replicate your way of defining the DAG for a sagemaker training job. But, for this line:

`from sagemaker.amazon.amazon_estimator import get_image_uri`

I get this error:

`Cannot find reference 'get_image_uri' in 'amazon_estimator.py' `.

Is it defined in any specific version? Or would you have any suggestions for resolving this error, please?

Thanks

**Comment by mpdominguez** [comment]
Hi! the version of the sagemaker SDK that this post uses is v1.72. Check by deploying the cloudformation script and then editing based on that.
